version: '3'

services:
    php:
        container_name: bingo_kata-php
        build: docker-php-fpm
        restart: unless-stopped
        ports:
            - "9001:9001"
        volumes:
            - .:/app:delegated
