version: '3'

services:
    php:
        container_name: bingo_kata-php
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        ports:
            - "9001:9001"
        volumes:
            - .:/app:delegated